- windows/installer-source/KaliteSetupScript.iss
The installer should now upgrade correctly.
> Fixed Uninstallation

- windows/.gitignore
- windows/installer-source/KaliteSetupScript.iss
Main GUI will hide during the uninstall process (on update);
The installer will wait for all scripts to terminate, before proceeding;
> Changes to the installer to make it smoother.

- osx/KA-Lite Monitor/KA-Lite Monitor/AppDelegate.m
- osx/KA-Lite Monitor/KA-Lite Monitor/README.md
Hi @aronasorman - this updates the documentation for the OSX installer.
> Update the documentation for the OSX installer.

- osx/KA-Lite Monitor/KA-Lite Monitor/AppDelegate.h
- osx/KA-Lite Monitor/KA-Lite Monitor/AppDelegate.m
- osx/KA-Lite Monitor/KA-Lite Monitor/en.lproj/MainMenu.xib
Hi @aronasorman - this fixes #63 - Can not Log Into KA-Lite post Install MAC.
We are still testing the issue and this fix so please hold on merging this yet.
Thanks.
ps: I hid the unused "?" button to fix learningequality/ka-lite#3838
> Add a "Reset App" button to reset the application settings.

- windows/installer-source/KaliteSetupScript.iss
> Hardcoded zip file name.

- windows/installer-source/KaliteSetupScript.iss
An issue with the encoding, presumably...?
> Fix up KaliteSetupScript.iss

- windows/installer-source/KaliteSetupScript.iss
Removes admin creation page and the validation code. Admin creation will now fall to the app itself.
> Remove admin creation page

- osx/setup.sh
Hi @aronasorman  this fixes #108
> Bad interpreter: No such file or directory

- windows/installer-source/KaliteSetupScript.iss
> Friendlier error message

- windows/installer-source/KaliteSetupScript.iss
Fixes https://github.com/learningequality/ka-lite/issues/4141 for Windows.
> Unpack assessment items in appropriate system-wide location

- osx/setup.sh
Hi @aronasorman - this fixes #126 - Run `kalite manage compileymltojson` when building the installer.
I've modified `setup.sh` to:
1. temporarily install `pyyaml==3.11` using `pyrun/bin/pip install pyyaml==3.11`
2. run `bin/kalite manage compileymltojson`
3. uninstall `pyyaml` before building the .dmg.
I'm currently uploading `KA-Lite-Monitor.dmg-2015-08-08a.zip` to GDrive and will broadcast on hipchat when done.
Here's a screenshot of the device page that's throwing the exception before:
Btw, this also fixes learningequality/ka-lite#4174 - Error: no module named yaml, while clicking device management page.
/cc: @djallado
> This fixes the `No module named pyyaml` issue when navigating the device page.

- osx/README.md
Hi @aronasorman  I updated the docs.
Branch `master`
The updated docs include:
* Steps to build the installer. .
* Manually build and test the application using Xcode.
> Update steps to build the installer

- osx/KA-Lite-Monitor/KA-Lite-Monitor/AppDelegate.m
Hi @aronasorman this fixes #153
> need to restart the app after setup

- osx/KA-Lite-Monitor/KA-Lite-Monitor/AppDelegate.m
Hello @aronasorman this fixes #154
>   Reset App must inform user if an anomaly is found in the user's environment.

- osx/setup.sh
Hi @cpauya and @aronasorman this fixes the #150
**Branch :** Master
**Expected Behaviour:** Able to make the standalone HTML files and path correctly the /bin/sphinx-build in the `pyrun` directory.
See Image as Demonstration. 
**Current Behaviour:** The /bin/sphinx-build in the `pyrun` directory is not path properly and cant create the standalone HTML files.
See Image as Demonstration.
> No such file or directory /bin/sphinx-build

- osx/KA-Lite-Monitor/KA-Lite-Monitor/AppDelegate.h
- osx/KA-Lite-Monitor/KA-Lite-Monitor/AppDelegate.m
- osx/KA-Lite-Monitor/KA-Lite-Monitor/en.lproj/MainMenu.xib
Hi @aronasorman this fixes #159
> Disable preferences tabs when osx app still processing

- windows/installer-source/KaliteSetupScript.iss
> Add icon for KA Lite executable

- osx/KA-Lite-Monitor/KA-Lite-Monitor/AppDelegate.h
- osx/KA-Lite-Monitor/KA-Lite-Monitor/AppDelegate.m
> Mac installer menu bar icon not set to "processing" while setup is running

- windows/bamboo-build.sh
> Create bamboo build script

- windows/bamboo-build.sh
Now we're versioning the installers repo, too. I pushed some changes to master which should be meant for 0.15.x.
> master into 0.15.x

- windows/README.md
> 0.15.x into master

- osx/setup-files/LICENSE
- osx/setup.sh
> Mac installer must add LICENSE to `setup-files`

- osx/README.md
@cpauya I updated the OS X `README.md`.
I add `wget` as another system requirement and modify the steps to manually build and test the application using `Xcode`. I also add sample on how to pass an `assessment` url when running `setup.sh`.
> Update OS X README.md

- osx/KA-Lite-Monitor/KA-Lite-Monitor/AppDelegate.m
- osx/KA-Lite-Monitor/KA-Lite-Monitor/Info.plist
@cpauya & @aronasorman this fixes #236
> Preferences dialog must be always on top

- osx/KA-Lite-Monitor/KA-Lite-Monitor/AppDelegate.m
@cpauya & @aronasorman  this fixes #114
I enabled the property to show icon on the dock. I've attached a screenshot.
> Show dock icon of the app.

- osx/KA-Lite/KA-Lite/Info.plist
- osx/setup-files/LICENSE
- osx/setup.sh
- windows/README.md
- windows/bamboo-build.sh
- windows/installer-source/KaliteSetupScript.iss
@cpauya I merged 0.15 branch to develop.
> Merge 0.15 branch to develop

- osx/KA-Lite/KA-Lite/en.lproj/MainMenu.xib
> Put version in KA-Lite Preferences dialog.

- osx/KA-Lite/KA-Lite/AppDelegate.m
> Use kalite executable when running commands in nstask class

- osx/KA-Lite/KA-Lite/AppDelegate.h
- osx/KA-Lite/KA-Lite/AppDelegate.m
- osx/KA-Lite/KA-Lite/en.lproj/MainMenu.xib
@cpauya this fixes #276 
Here's the sample screenshot of the preferences menu.
> OS X Application UX changes.

- osx/KA-Lite/KA-Lite/AppDelegate.h
- osx/KA-Lite/KA-Lite/AppDelegate.m
- osx/KA-Lite/KA-Lite/en.lproj/MainMenu.xib
- osx/README.md
- osx/setup-files/README.md
@cpauya this fixes #279 
I attached a sample screenshot of the preferences menu.
> Implement custom paths in preferences window

- osx/KA-Lite/KA-Lite/AppDelegate.m
- osx/post_installation.sh
> Support OS X "El Capitan"

- osx/KA-Lite/KA-Lite/AppDelegate.m
- osx/post_installation.sh
> Fix develop branch merge error

- debian/debian/ka-lite.scripts-common
> fix wrong user suggestion in software center #146

- windows/installer-source/KaliteSetupScript.iss
Fixes #297 on `0.15.x` different fix incoming on `develop` branch.
> 0.15.1 upgrade fix

- osx/post_installation.sh
Hi @aronasorman and @cpauya.
This is an additional fix of  #264 .
This fix will ensure that the org.learningequality.kalite.plist will be remove and replace a new one.
> Remove if the org.learningequality.kalite.plist file exists, then replace a new one.

- osx/KA-Lite/KA-Lite/AppDelegate.m
- osx/KA-Lite/KA-Lite/en.lproj/MainMenu.xib
@cpauya & @aronasorman this fixes #301 
I aligned the help button and text. I attached a sample screenshot.
> Help text for the custom data path control

- osx/KA-Lite/KA-Lite/AppDelegate.h
- osx/KA-Lite/KA-Lite/AppDelegate.m
- osx/KA-Lite/KA-Lite/en.lproj/MainMenu.xib
> Disabled apply button if no changes in the KA Lite preferences dialog.

- osx/KA-Lite/KA-Lite/AppDelegate.m
- osx/KA-Lite/KA-Lite/en.lproj/MainMenu.xib
@cpauya this fixes #327 
I created an alert dialog to notify and will not load the KA Lite application if kalite executable is not found,
> KA Lite application must not load if `kalite` executable is not found.

- osx/KA-Lite/KA-Lite/AppDelegate.h
- osx/KA-Lite/KA-Lite/AppDelegate.m
- osx/KA-Lite/KA-Lite/en.lproj/MainMenu.xib
- osx/ka-lite-remover.sh
- osx/post_installation.sh
@cpauya This fixes #332 
I created the uninstall button in the KA Lite application dialog. I attached a sample screenshot below.
> Include Uninstall button in the Preferences dialog

- osx/KA-Lite/KA-Lite/AppDelegate.m
- osx/KA-Lite/KA-Lite/en.lproj/MainMenu.xib
@aronasorman & @cpauya  this fixes #338 
I show an alert window to display the help text.
> Tooltip help isn't too user friendly

- osx/post_installation.sh
Hi @aronasorman and @cpauya  this fixes #337 
I modified the `post_installation.sh` that removed the old assets, then run the management command so that it will replace the assets built by make assets.
> Replace the current assets with the newer ones.

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Second take on this. Definitely less confusing now, thanks @benjaoming!!! :+1: 
Now that I think of it, do test & dependencies items in PR template make sense here, on installers? Or should I leave them out?
> New templates for issues and PRs

- debian/debian/changelog
- debian/debian/ka-lite.scripts-common
- debian/debian/ka-lite.templates
- debian/debian/kalite.conf
- debian/test_manual.sh
So far just a minor version bump.
> Debian changes for 0.16.3

- debian/debian/changelog
> Debian 0.16.6

- debian/debian/changelog
Standard release procedure, nothing changed for this patch release.
> 0.16.7 changelog

- debian/debian/changelog
Changelog as released in PPA and .debs
> Changelog bump to 0.16.8

- debian/debian/changelog
Routine version bump for debian changelog
> Add changelog for 0.16.9

- debian/debian/changelog
Merging 0.16.x into master due to a conflict
> 0.16.x into master (conflicts)

- debian/debian/ka-lite.scripts-common
- debian/test.sh
> Removal of *pyc in debian installer

- windows/installer-source/KaliteSetupScript.iss
> Stop the KA Lite server during upgrade.
##
Hi @radinamatic can you verify the fix using this [windows installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMamRrcUlsbDg1SzQ).
Fixes #351 
/cc @benjaoming @cpauya @radinamatic
> Stop the KA Lite server during upgrade.

- debian/debian/changelog
Accumulated changes lifted from the latest .deb releases.
> Debian 0.17.2

- debian/copy_from_pkg.sh
- debian/debian/changelog
- debian/debian/ka-lite.scripts-common
- debian/ppa-copy-packages.py
I seem to have missed adding changes from 0.17.4
Also introducing 0.17.5b1 in this.
n/a
> PR is considered WIP (work in progress), until all TODOs are marked.
> Debian 0.17.4 and 0.17.5
