learningequality/ka-lite-installers

osx/ka-lite-on-pyrun.sh
Hi @aronasorman - this is the very initial script for #4 
Done:
* It downloads the official PyRun installer script and sets-up a minimal PyRun directory with Python 2.7.8 (more than 25mb) under `/tmp/ka-lite-on-pyrun/`.
ToDos:
* git clone ka-lite on the PyRun tmp folder
* modify ka-lite`s `/scripts/python.sh` script to point to PyRun`s `/bin/pyrun` folder so it uses the Python version of PyRun instead of the system Python.
=> Initial script to install pyrun and bundle ka-lite inside.

osx/KA-Lite Monitor/KA-Lite Monitor/AppDelegate.m, osx/setup.sh
Hi @aronasorman this fixes #3 - "Mac OS X .app file" issue that doesn't allow the user to click on the "Start KA Lite" menu option on fresh install as reported by @EdDixon during his testing.
This fix will now always enable the "Start KA Lite" menu.
To reproduce the issue:
1. Install the [Mac OS X installer](https://drive.google.com/open?id=0Bwf_-YL9LvlVaGxHX3RxQzVOVzQ&authuser=0) - get the version released 2015-04-06 7:44pm.
1. Go to Terminal and run `touch ~/.kalite/kalite.pid` - this will make the `bin/kalite status` command yield a "Invalid PID file (100)" message 
1. Launch the "KA-Lite Monitor.app" - this will not allow you to click on the "Start KA Lite" menu even when you do another setup or a fresh install.
1. Now install the [Mac OS X installer with …
=> Enable the "Start KA Lite" menu option for unknown statuses.

windows/README.md
Small change in one instruction:
Instead of replacing ka-lite folder, copy that folder to the root of this directory and run `make.vbs`
=> Instruction change.

osx/setup.sh
Hi @aronasorman - this fixes #31 - Only download the ka-lite zip if there's no ka-lite folder in build directory.
=> Download the ka-lite repo zip if there's no `ka-lite` folder in the build directory.

osx/KA-Lite Monitor/KA-Lite Monitor/AppDelegate.m, osx/KA-Lite Monitor/KA-Lite Monitor/en.lproj/MainMenu.xib
Hi @aronasorman - this initially fixes #30 - Make kalite executable anywhere.
Note: I will just copy the tasks from #30 for reference.
**Tasks**
Next step is to do the actual symlink and try to build a .dmg and test the built .app as per tasks above.
=> Set environment variables when preferences are applied.

osx/KA-Lite Monitor/KA-Lite Monitor/AppDelegate.m, osx/setup.sh
Hi @aronasorman - this fixes #42 Preferences dialog does not show on first run.
This shows the preferences dialog if the database or `local_settings.py` do not exist.
You can verify output at the `Console` app as per attached screenshot below (look for the "not found, must show preferences" log):
/cc: @EdDixon
=> Fix for preferences dialog does not show on first run.

osx/setup.sh
Hi @aronasorman - this fixes #40 Stop the build process if pip install failed.
Here is the screenshot if `pip install` failed.
=> Stop the build script if `pip install` failed.

osx/KA-Lite Monitor/KA-Lite Monitor/AppDelegate.m
Hi @aronasorman - this fixes #30 Make kalite executable anywhere.
It now starts the KA-Lite server properly from the icon or from the terminal with the `kalite` command.
I'm gonna do more testing with restarts to see if it still works.
=> Fix the issue where the environment variables are not set when running the kalite command.

windows/README.md, windows/installer-source/KaliteSetupScript.iss
Hi @aronasorman this fixes #53 
I updated the `python` installer version from `2.7.9` to `2.7.10` so that the `pip` will update also from `1.5.4` to `7.0.1`.
This is where the kalite  zip files are extracted.
=> Install pip dependencies when running ka lite windows installer

osx/KA-Lite Monitor/KA-Lite Monitor/AppDelegate.m, osx/KA-Lite Monitor/KA-Lite Monitor/en.lproj/MainMenu.xib
Hi @aronasorman - this fixes #63 - Can not Log Into KA-Lite post Install MAC.
The issue is now fixed by using the proper format for option arguments when calling `kalite manage setup --noinput --username=user --password=pass` as discussed on learningequality/ka-lite#3939.
For the `Reset App` button - I've also merged the multiple calls to `runRootCommands()` method so it will only ask the user once for the admin password.
/cc: @EdDixon
=> Fix issue where user cannot login after installation on Mac.

windows/installer-source/KaliteSetupScript.iss
=> Check if 64-bit before using 64-bit registry keys

osx/setup.sh, windows/installer-source/KaliteSetupScript.iss
Handles the case where `pip.exe` is not on the `C:` drive. Fixes #74 and fixes #81. Will test out on Windows 8. @radinamatic I'll upload an installer for you to try, as well.
=> Windows installer - don't assume drive letter for `pip.exe`

windows/README.md, windows/installer-source/KaliteSetupScript.iss
Update the installer to set the `ROOT_DATA_PATH` by environment variable. Also add instructions for building the installer. It's necessary to run collectstatic so that static-libraries are copied over... User might not have the permissions to create the static-directory after install. This handles both a new install and an upgrade case.
=> Windows - root data path fix

windows/installer-source/KaliteSetupScript.iss
Fixes #95. This is only so that the user has pip.exe available, so it's not a hard requirement. I know we wish to support Python 2.6 still, but given that 2.7.10 is bundled in the installer and apparently works on all supported versions of Windows, I felt it was ok.
=> Require python 2.7.9 on Windows

osx/setup.sh
Hi @aronasorman - this fixes #102 - Setup script extracts ka-lite source outside the working directory.
=> Extract `ka-lite.zip` inside the `temp` working directory.

windows/installer-source/KaliteSetupScript.iss
Remove the KALITE_ROOT_DATA_PATH variable set by the installer.
The change is not broadcast by inno setup, so currently running processes won't acknowledge the change.
=> Unset environment variable set by installation

osx/setup.sh
Hi @aronasorman this fixes #150 
I was able to modify the `setup.sh` for sphinx build and node installation for `pyrun`. This will enable the `Documentation` link in the Navbar
See the image below as demonstration
=> Enable KA-Lite documentation link  for mac installer

osx/setup.sh
Hi @cpauya and @aronasorman  this fixes #161 
**Steps updated and removed:**
>1. Include the steps to download the assessment.zip and copy it to `Xcode Resources` folder.
>1. Will not include the `ka-lite` folder to copy in the Xcode Resources folder
>1. Remove step on creating the `local_settings.py` based on `local_settings.default`.
>1. Remove this step " `Make ka-lite repo production-ready (delete .KALITE_SOURCE_DIR, etc).".
it is not necessary anymore. 
>1. Add this step "Uninstall pyyaml so it's not included in the .dmg to build."
=> Update comments and steps

windows/installer-source/KaliteSetupScript.iss
Fixes #160, and also ensures the uninstall shortcut in the start menu works.
The uninstall shortcut was misconfigured in [Icons].
Now it points to the correct .exe.
Changed some uninstall directives in [UninstallDelete].
Basically, all the directives could be collapsed into a single command.
If there is a reason to create a new directive for each subdirectory,
it certainly is not clear to me.
Finally, removed the `uninsneveruninstall` option on the {app}/ka-lite/content
directory. Downloaded content is now stored in the user's content root.
=> Remove everything on uninstall; Fix uninstall shortcut

windows/installer-source/KaliteSetupScript.iss
Fixes #123. Turned out to be really simple. Forces a restart after installation. Does not give the option of starting the app immediately.
=> Force restart after install

osx/KA-Lite-Monitor/KA-Lite-Monitor/AppDelegate.m, osx/setup.sh
Hi @aronasorman - this fixes #169 "mac 0.15 dev assets are not compiled".
We moved the step to run `pyrun setup.py install` after running the `node build.js` so that the `bundle*.js` files are included when copied inside the `pyrun-2.7` directory.
`bundle*.js` files are now bundled in the KA-Lite-Monitor.app:
```bash
cyril-lappy6:~ cyril$ cd /Applications/KA-Lite-Monitor.app/
cyril-lappy6:KA-Lite-Monitor.app cyril$ find ./ -name "bundle*.js"
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/coachreports/static/js/coachreports/bundles/bundle_coach_report.js
.//Contents/Resources/pyrun-2.7/lib/python2.7/site-packages/ka_lite-0.15.0-py2.7.egg/kalite/coachreports/static/js/coachreports/bundles/bundle_student_progress.js …
```
=> Hotfix/169 mac 0.15 dev assets are not compiled

osx/setup.sh
Hi @aronasorman - this fixes #182.
We now capture if download of `assessment.zip` failed and exit accordingly to prevent the build from continuing.
=> Check if download of assessment.zip succeeded.

windows/installer-source/KaliteSetupScript.iss
Called the setup mgmt command, but apparently the KALITE_ROOT_DATA_PATH
environment variable was not set properly -- the installer would have
to exit first for the change to be broadcast.
Instead, let the app handle the setup the first time it's started.
Fixes #178. Implements the solution I described in https://github.com/learningequality/installers/pull/188#issuecomment-144225204. @cpauya can you review/test this out? But hold off on merging, for now.
=> Remove setup mgmt command from installer

osx/setup.sh
@cpauya I changed the default assessment url of the `setup.sh` to `https://learningequality.org/downloads/ka-lite/0.15/content/khan_assessment.zip`. I attached the screenshot when running `setup.sh`.
=> Fix setup.sh to change default of second argument

windows/installer-source/KaliteSetupScript.iss
Edit: A WIP. Need to test this out comprehensively.
We avoid copying the files to a temp location first, since it could require
a lot of storage space and take a long time.
Fixes #179.
=> Copy 0.13.x files directly to .kalite dir

osx/KA-Lite/KA-Lite/AppDelegate.m, osx/build.sh, osx/pre_installation.sh
Hi @aronasorman, @cpauya and @djallado .
This fixes #282 
**Upgrade Checklist :**
=> Upgrade process for OS X installer 0.16.0

windows/README.md, windows/installer-source/KaliteSetupScript.iss
Submitted after mucking around with InnoSetup for some time.
Commit message:
```text
Instead of unpacking assessment items when creating the installer, which
results in a metric boat load of files (and causes wine+IS to choke) we
instead include khan_assessment.zip in the installer, and call
the unpack_assessment_zip mgmt command during the installation process.
We *must* reference the KALITE_SCRIPT_DIR environment variable directly
from the registry -- the environment for any process spawned by the
installer won't be updated until *after* the installer exits, so e.g.
%KALITE_SCRIPT_DIR% won't expand as expected.
```
=> Windows -- Unpack assessment items during install

osx/KA-Lite-Monitor/KA-Lite-Monitor.xcodeproj/project.pbxproj
@cpauya This a hotfix to make `El Capitan` run `setup.sh` without error.
**Screenshot:** running `setup.sh` in `El Capitan`.
=> Change Base SDK to Latest to make El Capitan run setup.sh.

windows/installer-source/KaliteSetupScript.iss
Fixes #297 on develop. The ka-lite app now handles copying a pre-built database (if it exists).
=> Don't copy empty db; ka-lite app now handles it

osx/KA-Lite/KA-Lite/AppDelegate.h, osx/KA-Lite/KA-Lite/AppDelegate.m, osx/KA-Lite/KA-Lite/en.lproj/MainMenu.xib
@cpauya this fixes #301 
I add another window to show the help text for the KA Lite data path. 
I attached a sample screenshot of the KA Lite preferences dialog.
=> Help text for the custom data path control

osx/ka-lite-remover.sh, osx/post_installation.sh
Hi @cpauya, @aronasorman and @djallado  this fixes #308
**This fix include the following:**
> Remove `org.learningequality.*.plist` file in the root and home directory.
> Load assessment item before issue `kalite manage setup --noinput`
See attach screen shot for demo.
=> Load assessment item before setup

windows/installer-source/KaliteSetupScript.iss, windows/scripts/add_systemstart_task.bat, windows/scripts/remove_systemstart_task.bat
Fixes #106 -- should start at boot now.
These scripts are updated, and should be removed from the ka-lite repo... they do no good there!
commitmsg
```
Copy them, and instead of referencing the now defunct bin/windows/kalite.bat
script, use the included kalite.bat script in the ..\Python27\Scripts\ dir.
```
=> Add systemstart task scripts to installer repo, fix bug

windows/gui-source/KA Lite/config.h, windows/installer-source/KaliteSetupScript.iss, windows/scripts/add_systemstart_task.bat
Still a WIP. Will fix #321.
Todo:
Will appreciate a code review. I am but an egg with C++\Windows dev. Willing to discuss in great detail.
=> [Windows] Change CONFIG.dat file location, behavior

windows/installer-source/KaliteSetupScript.iss
Remove the old scheduled task run as SYSTEM user, since from now it should be run as current user.
Should fix #345.
=> Delete old KALite start-at-boot task when upgrading to 0.16

osx/KA-Lite/KA-Lite/AppDelegate.m, osx/KA-Lite/KA-Lite/en.lproj/MainMenu.xib, osx/ka-lite-remover.sh
Hi @aronasorman - this fixes #23.
We now include the following preferences plist files when cleaning-up during setup or when uninstalling KA-Lite:
``` bash
$HOME/Library/Preferences/org.learningequality.kalite.plist
$HOME/Library/Preferences/FLE.KA-Lite-Monitor.plist"
```
Must Test on:
Please hold on merging this until I've tested on the above platforms.
=> Include the preferences plist files when cleaning-up or uninstalling.

windows/scripts/add_systemstart_task.bat
Fixes #345. Commit messages below:
```text
This is because Windows will refuse to start the KA Lite server
in the background *before* the user logs in if the password is
not provided. Note that passing the /np (no password) flag will
cause the task to *attempt* to start, but it will fail because
"no logon server could process the request".
```
```
It's run as the SYSTEM user, which has been an error since
0.13.0 -- see #345. Delete it so we can start fresh.
```
=> [Windows] Fix new scheduled task behavior

windows/installer-source/KaliteSetupScript.iss
Using the --foreground option prevents database
access, which is an error if `setup` has not been
run (which is the case at install time).
=> Unpack content pack with correct option

osx/README.md, osx/ka-lite-remover.sh, osx/post_installation.sh, osx/release-docs/README.md
- Corrects the check for number of KA Lite application instances during pre-install and uninstall.
- Also restores the missing step 5 message during post-install at the Console app.
- Fixes #373
- Fixes #369
Download the [latest build 91 at Bamboo](http://dungeon.learningequality.org/browse/KL-MT16-91) which points to the hot fix branch for this PR.
/cc: @aronasorman @radinamatic
=> Correct the check for number of KA Lite application instances during pre-install.

osx/KA-Lite-Packages/KA-Lite.pkgproj, osx/KA-Lite-Packages/docs/INTRODUCTION.rst.rtfd/TXT.rtf, osx/KA-Lite-Packages/docs/README.rst.rtf, osx/KA-Lite/KA-Lite/AppDelegate.m, osx/README.md, osx/ka-lite-process-check.sh, osx/ka-lite-remover.sh, osx/release-docs/README.md, osx/release-docs/RELEASE_NOTES.md
- Added a script to check for a running KA Lite and use that as a requirement for the installer before continuing.
- Fixes #369 
- Also fixes #380
- Also fixes https://github.com/learningequality/ka-lite/issues/4964
Download the [build 95 on Bamboo](http://dungeon.learningequality.org/browse/KL-MT16-95) to test this hot fix.
1. If you don't have KA Lite installed, download and install a previous KA Lite OS X installer from http://pantry.learningequality.org/downloads/ka-lite/0.15/installers/mac/.
1. Run the KA Lite application, no need to input an admin account, just leave it running.
1. Install the .pkg from Bamboo as per above.
1. Click the Continue button when prompted with the "This package will run a program to determine if the software can be installed." message.
1. It should notify …
=> Run a script to check if KA Lite is loaded before continuing with installation.

debian/docker/Dockerfile, debian/docker/README.md
Creates a docker image for building unsigned debs. Can be modified to build a signed deb for release.
See the included readme file.
=> Create docker image for building debs

osx/build.sh, osx/post_installation.sh
Run `pip install -r requirements_sphinx.txt` to fix the failing OS X build.
- Fixes #382
- Also Fixes learningequality/ka-lite#5054 by running `pyrun manage collectstatic --noinput` during post-install.
* Download the [artifact from build 104 at Bamboo](http://dungeon.learningequality.org/browse/KL-MT16-104) to test this PR.
=> Run `pip install -r requirements_sphinx.txt` to fix the failing OS X build.

windows/README.md
@MCGallaspy, This fixes #398 
https://github.com/learningequality/installers/tree/master/windows
=> Modify the instructions in building "KALiteSetup.exe" in windows README.

osx/build.sh
- Fixes #401
- The new release of `install-pyrun.sh` is creating an issue when building the KA-Lite OS X installer.
To fix this issue I use the older version of eGenix PyRun prior to the latest release.
=> Temporary fix of pyrun that failed to install setuptools-pt3

debian/debian/kalite.conf
We've been serving this as an assumption that the user would download an assessment item pack during debconf execution.
This is no longer relevant and actually blocks serving the right folder :)
=> Don't serve the old assessment item path

osx/KA-Lite/KA-Lite/AppDelegate.h, osx/KA-Lite/KA-Lite/AppDelegate.m
This fixes KA Lite server taking so long to start on El Capitán when using the latest English content packs with subs.
##
Hi @radinamatic can you test again, the latest OS X [installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMVmhwTHpmOHVQVHM) with the updated English content pack. 
/cc @radinamatic  @cpauya @mrpau-eduard
=> KA Lite server taking so long to start on El Capitán

osx/KA-Lite-Packages/docs/README.rst.rtf, osx/KA-Lite/KA-Lite/README.md, osx/README.md, osx/dmg-resources/README.md, osx/release-docs/README.md, osx/release-docs/RELEASE_NOTES.md
> I updated the README.md and the release notes for 0.17.x release.
/cc @cpauya @mrpau-eduard
=> Update KA Lite OS X installer documentation for 0.17.x release

windows/installer-source/KaliteSetupScript.iss
> This fixes the issue when newly build English content pack with subtitles are not showing in the KA Lite windows application. 
Hi @radinamatic Can you test this using this [windows installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMaUwtdXJnSC1jdmc).
/cc @cpauya  @mrpau-eduard
=> Fix not loading English content pack with subtitles using the KA Lite windows application.

osx/KA-Lite-Packages/KA-Lite.pkgproj, osx/build.sh, osx/ka-lite-remover.sh, osx/post_installation.sh
> Use well known location for bundled english content pack.
> Fix build script, step arrangements.
Fixes #438 
/cc @cpauya @mrpau-eduard
=> Use well known location for bundled english content pack

debian/debian/changelog, debian/debian/ka-lite.service
Lacking a mandatory section, obviously because the auto-generated file, I copied was broken.
Systemd is becoming the standard on most major distros, so we better be up to speed. Also this for consideration: https://twitter.com/systemdsucks
Tested in Ubuntu 16.04
https://github.com/learningequality/ka-lite/issues/5423
> PR is considered WIP (work in progress), until all TODOs are marked.
=> Fixing systemd

osx/KA-Lite/KA-Lite/AppDelegate.m
> This fixes the KA Lite Mac application high CPU usage.
Fixes #445 
Here's the [osx installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMVXNLZVlYOFFMaTQ) to test this PR.
/cc @radinamatic @cpauya
=> Fix KA Lite Mac application high CPU usage .

osx/KA-Lite-Packages/docs/INTRODUCTION.rst.rtfd/TXT.rtf, osx/KA-Lite-Packages/docs/README.rst.rtf, osx/KA-Lite-Packages/docs/SUMMARY.rtfd/TXT.rtf, osx/build.sh
> This will fix the hardcoded KA Lite version at the `.pkg`  installer.
Fixes #426
=> Fix hardcoded KA Lite version at mac OS X installer.

debian/debian/startup/ka-lite.init, debian/test.sh
=> Fixing `service ka-lite status` command

osx/ka-lite-python-version-check.sh, osx/post_installation.sh
Used `python2 --version` command  to check the python version installed in the system.
If that command didn't exist it will default to `python --version`.
Fixes #470 
cc\ @cpauya
=> Installing python with Homebrew fails

windows/installer-source/KaliteSetupScript.iss
The command `retrievecontentpack --foreground` was removed on 0.17.5 release.
[#5579](https://github.com/learningequality/ka-lite/pull/5579)
> PR is considered WIP (work in progress), until all TODOs are marked.
=> Remove —foreground at the retrievecontentpack command.
